### Obtener publicaciones
GET http://localhost:3000/

### Crear publicacion
POST http://localhost:3000/create
Content-Type: application/json

{
    "title": "titulo 22",   
    "body": "body 22"
}

### Buscar publicacion por id
GET http://localhost:3000/id/65d2694014692a48a881ddc0

### Buscar publicacion por titulo
GET http://localhost:3000/title/titulo 1

### Actualizar una publicacion
PUT http://localhost:3000/id/65d2694014692a48a881ddc0
Content-Type: application/json

{
    "title": "titulo actualizado5",
    "body": "body actualizado5"
}

### Eliminar una publicacion
DELETE http://localhost:3000/id/65d2694014692a48a881ddc0

### Obtener publicaciones con paginacion
GET http://localhost:3000/postsWithPagination?page=3